# Generated by Django 5.2.5 on 2025-08-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_expense',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
