# Generated by Django 5.2.5 on 2025-08-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
