# Generated by Django 5.2.5 on 2025-08-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_expense_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_expense',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
