# Generated by Django 5.2.5 on 2025-08-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_expense_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_income',
            name='credit_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='total_income',
            name='debit_amount',
            field=models.IntegerField(default=0),
        ),
    ]
